name: flutter_training
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints:
    git:
      url: https://github.com/yumemi-inc/flutter-yumemi-lints
      ref: main

flutter:
  uses-material-design: true
